### ISSUE TITLE
Usar decorators (draper) para formatear montos y tener nombres de cuenta human friendly

### ISSUE THREAD

**Issue by ldlsegovia** [platanus/ledgerizer#9]
Actualmente tenemos `Ledgerizer::Account`s que tienen un `name` que es un `symbol` y `Ledgerizer::Entry`s que tienen un `code`. Si queremos mostrar un listado de cuentas y entries, veríamos esos códigos feos. Se me ocurre que podríamos tener por cada modelo un decorator que tenga métodos: `human_name` y  `human_code` que permita mostrar nombres desde los locales.  Por ejemplo si tengo la definición:

```ruby
Ledgerizer.setup do |conf|
  conf.tenant(:portfolio) do
    conf.asset :bank
    conf.liability :funds_to_invest
    conf.liability :to_invest_in_fund

    conf.entry :user_deposit, document: :user_deposit do
      conf.debit account: :bank, accountable: :bank
      conf.credit account: :funds_to_invest, accountable: :user
    end

    conf.entry :user_deposit_distribution, document: :user_deposit do
      conf.debit account: :funds_to_invest, accountable: :user
      conf.credit account: :to_invest_in_fund, accountable: :user
    end
  end
end
```

Me gustaría poder definir en locales:

```yaml
ledgerizer:
  tenant:
    portfolio:
      accounts:
        bank: Banco
        funds_to_invest: Fondos por invertir
        to_invest_in_fund: Fondos por invertir
      entries:
        user_deposit_distribution:
          code: Distribución
        user_deposit:
          code: Depósito
```

Entonces si uno hace `account.decorated.human_name => "Banco"` 

También estaría bueno que podamos definir por cada currency como mostrar montos. Entonces después podríamos hacer:  `line.decorated.human_amount => CLP 5.000`
